### ISSUE TITLE
Move to pitop module namespace

### ISSUE THREAD

**Issue by m-roberts** [pi-top/pi-top-Python-SDK#8]
## TODO
- [x] Rename package to ```pitop.pma``` module
- [x] Remove PMA prefix from all components
- [x] Add backwards support with `python3-pt-pma-deprecated` (soft link to `ptpma` and PMA prefixed components)
